markabrahams/node-net-snmp

index.js

**I replaced req.dgram.bind with this.dgram.bind** because when calling the createSession method, it creates a new Session object and it crashes with an error such as:
c:\Snmp-Test\node_modules\net-snmp\index.js:599
req.dgram.bind (this.sourcePort, this.sourceAddress);
^
ReferenceError: req is not defined
at new Session (c:\ANF\Asintel.Spi-Snmp\node_modules\net-snmp\index.js:599:3)
at Object.exports.createSession (c:\ANF\Asintel.Spi-Snmp\node_modules\net-snmp\index.js:1440:9)
at Object.<anonymous> (c:\ANF\Asintel.Spi-Snmp\src\trap.js:16:20)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at …

Solving ReferenceError: req is not defined

---

README.md
index.js
test/varbinds.js

This should help address #21, some older devices don't support 32 bit ids, it's somewhat common to see devices only handle 16 bit ids.  The C net-snmp solves this with the `--16bitIDs=1` flag.  I tried to follow that pattern.

Add support of 16bit ids to help interoperate with older devices.

---

index.js

For me at least this fixes: https://github.com/markabrahams/node-net-snmp/issues/64
Issue is that some devices do not set the `msgAuthoritativeEngineBoots` and `msgAuthoritativeEngineTime` fields on the first report PDU in response to initial discovery, and a second request / report is required to get those before the actual request can proceed.
A possible simpler change would be to always store the original PDU on the req, as in this patch:
```
diff --git a/index.js b/index.js
index aba8bf1..eef7d3b 100644
--- a/index.js
+++ b/index.js
@@ -2490,6 +2490,7 @@ Session.prototype.sendV3Req = function (pdu, feedCb, responseCb, options, port)
var reqOptions = options || {};
var req = new Req (this, message, feedCb, responseCb, reqOptions);
req.port = port;
+       req.originalPdu = pdu; …
```

Fix issue where some agents use a 2nd report PDU to perform time synchronization

---

index.js

OK, this fixes https://github.com/markabrahams/node-net-snmp/issues/68 for me, without breaking the initial double report PDU handling unlike my previous attempt in https://github.com/markabrahams/node-net-snmp/pull/69. Have tested against 2 Cisco devices and a unix machine using the standard net-snmp library successfully.
There's a flag on the req to say whether we allow a report PDU to be the response or not - it is true for initial discovery requests, true if we receive a report PDU without the time sync fields set, and true for normal requests, but false if we just received a report PDU with the time fields, to avoid us allowing a loop where we keep sending a request and the device keeps replying with a report. See what you think...

Handle periodic report PDU packets on a long running session

---

lib/mib.js

Process OBJECT_IDENTIFIER with multiple nodes, reported on #72

fix oid and namespace with multi node

---

lib/mib.js

This adds support for Windows absolute paths (generated by `path.resolve(relativePath);`. The regex checks for a string starting with a letter (drive letter) followed by a colon followed by a back slash (Windows uses back slashes where Linux uses forward slashes).
Fixes #74

Support for absolute Windows paths

---

index.js

I had a single index table like follows:
```js
var myTableProvider = {
name: 'smallIfTable',
type: MibProviderType.Table,
oid: '1.3.6.1.2.1.2.2.1',
tableColumns: [
{
number: 1,
name: 'ifIndex',
type: ObjectType.Integer,
},
{
number: 2,
name: 'ifDescr',
type: ObjectType.Integer,
},
{
number: 3,
name: 'ifType',
type: ObjectType.Integer,
},
],
tableIndex: [
{
columnName: 'ifIndex',
},
],
};
var mib = agent.getMib();
mib.registerProvider(myTableProvider);
mib.addTableRow('smallIfTable', [0, 10, 6]); // of interest
mib.addTableRow('smallIfTable', [2, 11, 6]);
mib.addTableRow('smallIfTable', [3, 12, 8]);
```
My first row had the value `0` for the index column, when I called row specific methods with `rowIndex: [0]`, it would throw an error. This was because of a falsy check instead of a null …

Bug fix for when the index value contains 0

---

index.js

mib getColumnProvider has a typo when it cant find a columnName

fixed columnNumber check in getColumnProvider

---

.eslintrc
example/cisco-device-inventory.js
example/mib-parser.js
example/option-parser.js
example/receiver-lcd.js
example/snmp-get-bulk.js
example/snmp-receiver.js
example/snmp-set.js
example/snmp-table-columns.js
example/snmp-table.js
index.js
lib/mib.js
package.json
test/varbinds.js

This was inspired by https://github.com/markabrahams/node-net-snmp/pull/115 but tunes the rules and fixes some code to eliminate almost all lint errors relative to the included config.
• Adds eslint with a simple config (with no extra dependencies apart from eslint itself) which does not raise too many errors or warnings when linting the existing codebase.
• Fixes some of the simplest errors highlighted by eslint - some are simply stylistic like mixed spaces/tabs or brace styles, and others are potential causes of bugs or indeed actual bugs such as undefined vars or the use of the wrong var name.
• Adds a script config to the package so eslint can easily be run with `npm run lint`
There are still two problems reported by the eslint config in this PR, as follows:
``` …
```

Add eslint configuration and fix lint errors

---

README.md

Convert existing indented code blocks to fenced syntax which enables syntax highlighting in Markdown. Diff ist best viewed with whitespace-only changes hidden on the GitHub UI.

Add syntax definitions to README code blocks

---

index.js

`ResponseInvalidError` is passed to the user's callback. It is difficult and unreliable, however, to parse English text error messages, particularly when they are dynamically generated (not static) strings, and in any case, there's no guarantee that the strings won't change in the future for arbitrary reasons.
To remedy this situation, I have created `ResponseInvalidCode` values which are passed to the `ResponseInvalidError` constructor, so that when the callback receives the error, it can look at the code rather than the text string. Additionally, there is an optional `info` parameter to that constructor, to provide additional information to the user. In my case, I am required to send an SNMPv3 inform whenever there is an authentication error, so I need the details of the user provided …

Response invalid code

---

index.js

This seems to do the trick, re: #175. 
Would please look at the code immediately after this, though, to confirm it's correct? It's prepending a length, which seems reasonable, but `snmpwalk` then doesn't parse it as I'd expect. Is that length always supposed to be prepended?
For example, 
```
...
IPV6-MIB::ipv6IfStatsOutMcastPkts.13 = Counter32: 54701
IPV6-MIB::ipv6IfStatsOutMcastPkts.14 = Counter32: 54701
IPV6-MIB::ipv6IfStatsOutMcastPkts.15 = Counter32: 117308
IPV6-MIB::ipv6AddrPfxLength.1.'..........BN...J'.168 = INTEGER: 64 bits
IPV6-MIB::ipv6AddrPfxLength.2.'.....#B.........'.1 = INTEGER: 64 bits
IPV6-MIB::ipv6AddrPfxLength.2.'................'.1 = INTEGER: 64 bits
IPV6-MIB::ipv6AddrPfxLength.2.'..........B....O'.169 = INTEGER: 64 bits
...
```
Each of the PfxLength OIDs has a …

getOidAddressFromValue: allow value to be buffer too, not just string

---

index.js

GetNext should always return a value that is >= start oid, but this is not always the case.
E g, if a tree has nodes nnn.2.2 and nnn.2.4 (with values at nnn.2.2.0 and nnn.2.4.0),
but not nnn.2.3, and nnn.2.3 is requested, GetNext will return 2.2.0 instead of the expected 2.4.0.
The proposed code fixes that case by letting Mib.getTextNode return the last descendant.
getTreeNode is only used from Agent/Subagent.getNext, and the relevant code path is executed only if
the node suggested is not in the tree, so changing getTreeNode seems safe enough.

Fixup getNext when called for a non-node

---

index.js

Changes the time sync check from
`! snmpEngineBoots || ! snmpEngineTime`
which seems to be incorrectly require time sync from devices reporting an engine uptime but zero engine boots, to
`! snmpEngineBoots && ! snmpEngineTime`

Fix logic for v3 time syncronization needed

---

README.md
index.js

This is a set of improvements to the SNMPv3 cryptography code, including
- Add support for the SHA2 family authentication protocols (sha224, sha256, sha384, sha512) specified in RFC 7860.
- Fix a data corruption issue in DES decryption due to inappropriate use of a padding removal feature.

Implement SHA2, fix DES, and some crypto-related cleanups

---

README.md
index.js

1. The ENonRepeaterCountMismatch error is eliminated since the conditions where it was generated correspond to perfectly valid responses that you're pretty much guaranteed to run into if you use multiple repeaters and a large enough maxRepetitions count.
2. backwardsGetNexts now properly prevents EOutOfOrder errors for all of the varbinds (previously it failed to do so for non-repeaters).
3. The OID ordering for repeaters is now checked properly if backwardsGetNexts is false.
4. The OID for error responses is now checked if reportOidMismatchErrors is true.

Rewrite getBulk's response handling

---

index.js

Fixed wrong value check in the castSetValue function, that caused an exception to be raised when sending a set request for a IPAddress variable.
Fixes #211

Fixed wrong value validation for IP Address type

---

lib/mib.js

This supports the valid syntax where a type constraint specified in parens or braces joins the type specifier with no whitespace in between. E.g., previously
```
DisplayString(SIZE (2..10))
```
was parsed as a single symbol.  There was a special case for INTEGER, but this did not extend to Integer32 etc.  This patch generalizes the INTEGER case to tokenize upon seeing a '(' or '{' that open an outer group.

Mib lexer: Split name followed by group into separate symbols

---

index.js

Length constraints were not being applied when handling sets as the constraints object mistakenly used `size` rather than `sizes` which is what the applying code expects.
Also, at least in my latest node version, checking for `length` in a string threw an exception; so I changed it to an undefined check.

Fix string size constraints

---

index.js
lib/mib.js

Read standard TCs from SNMPv2-TC and update MIB loader and constraint logic to support SYNTAX elements that reference `TEXTUAL-CONVENTION`s. Also support constraints derived from range `(N..M)` `(A..B | C..D | ...)` and size `(SIZE (N..M))` specifiers in `TEXTUAL-CONVENTION`s.

Support type constraints via textual conventions

---

index.js
test/varbinds.js

Reading uint 32 with missing leading byte required by
ASN.1 BER will add the leading byte.
closes #233

More tolerant parsing in `readUint32`

---

index.js

Trivial fix for issue: [240 - session.subtree: feedCallback return value not checked](https://github.com/markabrahams/node-net-snmp/issues/240)

Fix session.subtree callback: abort for return value true

---

lib/mib.js

Add support for out-of-order object definitions within a MIB module by:
- Adding array `unresolvedObjects` to keep track of unresolved object names during parsing.
- Changing `getOidAndNamePaths()` to always return partial OID/namespace. Unresolved object name is returned as `unresolvedObject` if parent is not found, or parent has partial OID/namespace (ancestor of a broken parent object).
- Adding `unresolvedObject` to array `unresolvedObjects` if it is returned.
- Iterating through array `unresolvedObjects` after parsing has finished (if not empty), and attempting OID/namespace reconstruction.
- Printing console warnings for all objects that are affected by an unresolvable OID lineage (only if reconstruction fails).
These changes only affect cases where parent is not found. Any ordinary …

Add MIB parsing support for out-of-order object definitions

---

index.js

Came across issue with the marshalling of INTEGER/Integer32 values with AgentX.  Negative values are rejected by the buffer.writeUInt32BE(val) call as out of range (which is correct for UInteger32 and the like, but not for signed 32 bit integers).
Simple fix to switch to using buffer.writeInt32BE(val) for the Integer type.

Fix for error with negative ints on AgentX

---

index.js

The DEBUG mode is currently just a global flag, but can be influenced by constructor options for various classes.  Ideally there would be a debug toggle for each class, but that may be overkill.  This at least now allows a debug flag set in one class to not be killed when another is constructed without its debug flag set.  Another option would be to leverage the NODE_DEBUG style of enabling.

debug: Don't clear DEBUG setting based of ctor options and use test runner trace functions if present

---

index.js

This provides a way to workaround the change of behaviour introduced by the deferred registration update.  Constraints for SNMPv2-TC defined textual conventions like DisplayString seem to get preempted by the subsequent definitions as plain OCTET STRING in RFC MIBs.
This feature allows the user to select upon which base MIBs they depend explicitly so as not to get any surprises or unexpected type overrides.
Example usage to select just the SNMPv2 MIBs:
```js
snmp.createModuleStore({
baseModules: [
'SNMPv2-SMI',
'SNMPv2-CONF',
'SNMPv2-TC',
'SNMPv2-MIB',
],
});
```

ModuleStore: Allow to configure base modules.
